import { useEffect, useState } from "react";
import UserDialog from "./UserDialog";
import ProductAdminPanel from "./ProductAdminPanel";
import OrderManagementPanel from "./OrderManagementPanel";
import API_URL from "./api";
import { t } from "./i18n";
import { motion } from "framer-motion";

const api = API_URL;
const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("24street_token")}` });

export default function AccountPanel({ user, onClose, onSignedIn, onLogout, language = "th" }) {
  const [profile, setProfile] = useState(user || {}); const [users, setUsers] = useState([]); const [message, setMessage] = useState("");
  useEffect(() => { if (user?.role === "admin") fetch(`${api}/api/users`, { headers: headers() }).then(r => r.json()).then(data => setUsers(data.users || [])); }, [user]);
  if (!user) return <UserDialog language={language} onClose={onClose} onSignedIn={onSignedIn} />;
  const saveProfile = async event => { event.preventDefault(); const response = await fetch(`${api}/api/users/me`, { method: "PATCH", headers: headers(), body: JSON.stringify({ name: profile.name, phone: profile.phone }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message); localStorage.setItem("24street_user", JSON.stringify(data.user)); onSignedIn(data.user); setMessage(t(language, "profileSaved")); };
  const changeRole = async (id, role) => { const response = await fetch(`${api}/api/users/${id}`, { method: "PATCH", headers: headers(), body: JSON.stringify({ role }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message); setUsers(users.map(item => item.id === id ? data.user : item)); };
  const logout = async () => { try { await fetch(`${api}/api/users/logout`, { method: "POST", headers: headers() }); } finally { onLogout(); } };
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 overflow-y-auto bg-ink/60 p-4" onMouseDown={onClose}><motion.section initial={{ y: 16, scale: 0.99 }} animate={{ y: 0, scale: 1 }} exit={{ y: 10, scale: 0.99 }} transition={{ type: "spring", stiffness: 300, damping: 28 }} className="mx-auto my-6 w-full max-w-3xl border-2 border-ink bg-paper p-6 md:p-10" onMouseDown={event => event.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] tracking-[.2em]">{user.role === "admin" ? "ADMIN CONTROL CENTER" : t(language, "account").toUpperCase()}</p><h2 className="mt-2 font-display text-5xl">HELLO, {user.name}</h2></div><button className="text-4xl leading-none" onClick={onClose}>×</button></div><form className="mt-8 grid gap-4 border-y-2 border-ink py-6 md:grid-cols-2" onSubmit={saveProfile}><label className="text-xs">{t(language, "name").toUpperCase()}<input required value={profile.name || ""} onChange={e => setProfile({ ...profile, name: e.target.value })} className="mt-2 w-full border border-ink bg-paper p-3" /></label><label className="text-xs">{t(language, "phone").toUpperCase()}<input value={profile.phone || ""} onChange={e => setProfile({ ...profile, phone: e.target.value })} className="mt-2 w-full border border-ink bg-paper p-3" /></label><p className="text-xs md:col-span-2">{user.email} · {user.role.toUpperCase()}</p><div className="flex gap-3"><button className="w-fit bg-ink px-5 py-3 text-xs text-paper">{t(language, "saveProfile").toUpperCase()}</button><button type="button" className="border border-ink px-5 py-3 text-xs" onClick={logout}>{t(language, "logOut").toUpperCase()}</button></div>{message && <p className="self-center text-xs">{message}</p>}</form><OrderManagementPanel user={user} />{user.role === "admin" && <><section className="mt-8"><p className="text-[10px] tracking-[.2em]">ADMIN · USER MANAGEMENT</p><h3 className="mt-2 font-display text-4xl">{t(language, "members").toUpperCase()}</h3><div className="mt-4 overflow-x-auto border border-ink"><table className="w-full text-left text-xs"><thead className="border-b border-ink"><tr><th className="p-3">NAME</th><th className="p-3">EMAIL</th><th className="p-3">ROLE</th></tr></thead><tbody>{users.map(member => <tr className="border-b border-ink last:border-0" key={member.id}><td className="p-3">{member.name}</td><td className="p-3">{member.email}</td><td className="p-3"><select value={member.role} disabled={member.id === user.id} onChange={e => changeRole(member.id, e.target.value)} className="border border-ink bg-paper p-1"><option value="customer">Customer</option><option value="admin">Admin</option></select></td></tr>)}</tbody></table></div></section><ProductAdminPanel /></>}</motion.section></motion.div>;
}
