import ResilientImage from "./ResilientImage";
import { t } from "./i18n";
import { motion } from "framer-motion";

const money = value => `฿${Number(value).toLocaleString("th-TH")}`;
const validCheckoutItem = item => /^[a-f0-9]{24}$/i.test(String(item.id)) && Boolean(item.sku) && item.available !== false && Number(item.stock) >= item.quantity;

export default function BagDrawer({ items, onClose, onChange, onCheckout, language = "th" }) {
  const subtotal = items.reduce((total, item) => total + item.price * item.quantity, 0);
  const delivery = subtotal >= 1500 ? 0 : 50;
  const canCheckout = items.length > 0 && items.every(validCheckoutItem);
  return <motion.aside initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.22 }} className="fixed inset-0 z-50 flex justify-end bg-ink/60" onMouseDown={onClose}>
    <motion.section initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", stiffness: 300, damping: 32 }} className="h-full w-full max-w-md overflow-y-auto bg-paper p-6 md:p-8" onMouseDown={event => event.stopPropagation()}>
      <div className="flex justify-between border-b-2 border-ink pb-5"><div><p className="text-[10px] tracking-[.2em]">{t(language, "selection").toUpperCase()}</p><h2 className="mt-2 font-display text-5xl">{t(language, "bag").toUpperCase()}</h2></div><button className="text-4xl leading-none" aria-label={t(language, "close")} onClick={onClose}>×</button></div>
      {!items.length ? <p className="py-12 text-sm">{t(language, "emptyBag")}</p> : <><div className="divide-y divide-ink">{items.map(item => <article className="flex gap-4 py-5" key={`${item.id}-${item.sku || item.size}`}><div className="grid h-20 w-16 shrink-0 place-items-center overflow-hidden bg-sage font-display text-lg"><ResilientImage src={item.image} alt={item.name} className="h-full w-full object-cover" fallback={<span>24</span>} /></div><div className="flex-1"><h3 className="font-display text-2xl">{item.name}</h3><p className="text-[10px]">{t(language, "size").toUpperCase()} {item.size}{item.color ? ` / ${item.color}` : ""}</p><p className="mt-1 text-sm">{money(item.price)}</p>{item.available === false || Number(item.stock) < item.quantity ? <p role="status" className="mt-2 text-xs text-red-700">{t(language, "unavailable")}</p> : null}<div className="mt-3 flex items-center gap-3"><button aria-label={`Decrease ${item.name} quantity`} className="border border-ink px-2" onClick={() => onChange(items.map(x => x.id === item.id && x.sku === item.sku ? { ...x, quantity: Math.max(1, x.quantity - 1) } : x))}>−</button><span className="text-xs">{item.quantity}</span><button aria-label={`Increase ${item.name} quantity`} disabled={item.quantity >= Math.min(20, Number(item.stock) || 0)} className="border border-ink px-2 disabled:cursor-not-allowed disabled:opacity-40" onClick={() => onChange(items.map(x => x.id === item.id && x.sku === item.sku ? { ...x, quantity: Math.min(20, Number(x.stock) || 0, x.quantity + 1) } : x))}>+</button><button className="ml-auto text-[10px] underline" onClick={() => onChange(items.filter(x => x.id !== item.id || x.sku !== item.sku))}>{t(language, "remove").toUpperCase()}</button></div></div></article>)}</div><div className="mt-4 border-t-2 border-ink pt-4 text-sm"><p className="flex justify-between"><span>{t(language, "subtotal")}</span><span>{money(subtotal)}</span></p><p className="mt-2 flex justify-between"><span>{t(language, "delivery")}</span><span>{delivery ? money(delivery) : t(language, "free").toUpperCase()}</span></p><p className="mt-3 flex justify-between font-display text-3xl"><span>{t(language, "total").toUpperCase()}</span><span>{money(subtotal + delivery)}</span></p></div>{!canCheckout && <p role="alert" className="mt-4 text-xs text-red-700">{t(language, "updateBag")}</p>}<motion.button disabled={!canCheckout} whileTap={canCheckout ? { scale: 0.97 } : undefined} className="mt-6 w-full bg-ink py-4 text-xs text-paper disabled:cursor-not-allowed disabled:opacity-50" onClick={onCheckout}>{t(language, "checkout").toUpperCase()} →</motion.button></>}
    </motion.section>
  </motion.aside>;
}
