const messages = {
  en: {
    home: "Home", shop: "Shop", story: "Story", account: "Account", bag: "Bag", categories: "Product categories", close: "Close",
    category: "Categories", all: "All", newArrival: "New arrival", tees: "T-shirts", hoodies: "Hoodies", sweatshirts: "Sweatshirts", pants: "Pants", shorts: "Shorts", bags: "Bags", headwear: "Headwear", underwear: "Underwear", accessories: "Accessories", jackets: "Shirting",
    viewCategories: "View categories", findUniform: "Find your uniform.", chooseCategory: "Choose a category to browse matching products.",
    loading: "Loading the collection…", retry: "Retry catalog", emptyCategory: "There are no products in this category yet.",
    size: "Size", color: "Color", quantity: "Quantity", price: "Price", details: "Details", addToBag: "Add to bag", available: "available", outOfStock: "Out of stock", noVariants: "This product has no purchasable variants yet.",
    checkout: "Checkout", selection: "Your selection", emptyBag: "Your bag is waiting for its first piece.", remove: "Remove", subtotal: "Subtotal", delivery: "Delivery", total: "Total", unavailable: "This option is unavailable or has insufficient stock. Remove it to continue.", updateBag: "Update or remove unavailable items before checkout.",
    deliveryDetails: "Delivery details", shipping: "Shipping method", payment: "Payment", standard: "Standard", express: "Express", cod: "Cash on delivery", promptpay: "PromptPay", promptpayHint: "After you place the order, secure checkout will create a PromptPay QR code for this total.", bankTransfer: "Bank transfer", bank_transfer: "Bank transfer", card: "Credit / debit card", promptpayDetail: "Secure QR checkout", cardDetail: "Secure card checkout", bankDetail: "Upload a transfer slip", freeShipping: "Free over 1,500", chooseFile: "Choose image file", uploadSlip: "Upload transfer slip", placeOrder: "Place order", orderReceived: "Order received", thankYou: "Thank you.", continueShopping: "Continue shopping", fullName: "Full name", phone: "Phone", email: "Email", streetAddress: "Street address", subdistrict: "Subdistrict", district: "District", province: "Province", postalCode: "Postal code", name: "Name", password: "Password", signIn: "Sign in", createAccount: "Create account", welcomeBack: "Welcome back", joinClub: "Join the club", saveProfile: "Save profile", logOut: "Log out", members: "Members", profileSaved: "Saved",
  },
  th: {
    home: "หน้าแรก", shop: "สินค้า", story: "เรื่องราว", account: "บัญชีผู้ใช้", bag: "ตะกร้าสินค้า", categories: "หมวดหมู่สินค้า", close: "ปิด",
    category: "หมวดหมู่", all: "ทั้งหมด", newArrival: "สินค้าใหม่", tees: "เสื้อยืด", hoodies: "เสื้อฮู้ด", sweatshirts: "เสื้อสเวตเชิ้ต", pants: "กางเกงขายาว", shorts: "กางเกงขาสั้น", bags: "กระเป๋า", headwear: "หมวก", underwear: "ชุดชั้นใน", accessories: "เครื่องประดับ", jackets: "เสื้อคลุม",
    viewCategories: "ดูหมวดหมู่สินค้า", findUniform: "ค้นหาสไตล์ที่ใช่", chooseCategory: "เลือกหมวดหมู่เพื่อดูสินค้าที่ตรงกัน", loading: "กำลังโหลดสินค้า…", retry: "โหลดสินค้าอีกครั้ง", emptyCategory: "ยังไม่มีสินค้าในหมวดหมู่นี้", size: "ไซส์", color: "สี", quantity: "จำนวน", price: "ราคา", details: "รายละเอียด", addToBag: "เพิ่มลงตะกร้า", available: "ชิ้น", outOfStock: "สินค้าหมด", noVariants: "สินค้านี้ยังไม่มีตัวเลือกที่สั่งซื้อได้", checkout: "ชำระเงิน", selection: "สินค้าที่เลือก", emptyBag: "เลือกสินค้าใส่ตะกร้าได้เลย", remove: "นำออก", subtotal: "ยอดสินค้า", delivery: "ค่าจัดส่ง", total: "ยอดรวม", unavailable: "ตัวเลือกนี้ไม่มีสินค้า หรือมีสินค้าไม่พอ กรุณานำออกเพื่อดำเนินการต่อ", updateBag: "กรุณาแก้ไขหรือนำสินค้าที่ไม่พร้อมจำหน่ายออกก่อนชำระเงิน", deliveryDetails: "ข้อมูลการจัดส่ง", shipping: "วิธีจัดส่ง", payment: "การชำระเงิน", standard: "มาตรฐาน", express: "ด่วน", cod: "ชำระเงินปลายทาง", promptpay: "พร้อมเพย์", promptpayHint: "หลังยืนยันคำสั่งซื้อ ระบบชำระเงินจะแสดงคิวอาร์พร้อมเพย์ตามยอดจริง", bankTransfer: "โอนเงินผ่านธนาคาร", chooseFile: "เลือกไฟล์รูปภาพ", uploadSlip: "อัปโหลดสลิปโอนเงิน", placeOrder: "ยืนยันคำสั่งซื้อ", orderReceived: "ได้รับคำสั่งซื้อแล้ว", thankYou: "ขอบคุณค่ะ", continueShopping: "เลือกซื้อสินค้าต่อ", fullName: "ชื่อ-นามสกุล", phone: "โทรศัพท์", email: "อีเมล", streetAddress: "ที่อยู่", subdistrict: "แขวง/ตำบล", district: "เขต/อำเภอ", province: "จังหวัด", postalCode: "รหัสไปรษณีย์",
  },
};

Object.assign(messages.th, {
  bank_transfer: "โอนเงินผ่านธนาคาร", card: "บัตรเครดิต / เดบิต", promptpayDetail: "ชำระผ่านคิวอาร์อย่างปลอดภัย", cardDetail: "ชำระด้วยบัตรอย่างปลอดภัย", bankDetail: "อัปโหลดสลิปโอนเงิน", freeShipping: "ฟรีเมื่อซื้อครบ 1,500 บาท",
  name: "ชื่อ", password: "รหัสผ่าน", signIn: "เข้าสู่ระบบ", createAccount: "สร้างบัญชี", welcomeBack: "ยินดีต้อนรับกลับ", joinClub: "สมัครสมาชิก", saveProfile: "บันทึกข้อมูล", logOut: "ออกจากระบบ", members: "สมาชิก", profileSaved: "บันทึกแล้ว",
  switchLanguage: "เปลี่ยนภาษา", free: "ฟรี", paymentSlipPrompt: "เลือกสลิปโอนเงินได้เลย เมื่อสร้างคำสั่งซื้อแล้ว คุณจะอัปโหลดสลิปเพื่อแนบกับคำสั่งซื้อได้", selected: "เลือกแล้ว", stockConfirmed: "ร้านค้าจะยืนยันราคาและสต็อกอีกครั้ง", placingOrder: "กำลังส่งคำสั่งซื้อ...", optional: "ไม่บังคับ",
});
Object.assign(messages.en, {
  switchLanguage: "Switch language", free: "Free", paymentSlipPrompt: "Select your transfer slip now. It will be attached securely when your order is placed.", selected: "Selected", stockConfirmed: "Final prices and stock are confirmed by the store.", placingOrder: "Placing order...", optional: "Optional",
  bankName: "Bank", accountNumber: "Account number", accountName: "Account name", promptpayNumber: "PromptPay number", promptpayQr: "PromptPay QR placeholder", paymentInfoMissing: "Store payment details are not configured. Contact the store before transferring.", notConfigured: "Not configured", paymentSlipRequired: "Upload your transfer slip before confirming the order.", invalidSlip: "Choose an image file up to 5 MB.", slipReceived: "Your transfer slip was attached to this order.", orderSuccessful: "Order successful", orderId: "Order ID",
});
Object.assign(messages.th, {
  bankName: "ธนาคาร", accountNumber: "เลขที่บัญชี", accountName: "ชื่อบัญชี", promptpayNumber: "หมายเลขพร้อมเพย์", promptpayQr: "พื้นที่แสดง QR พร้อมเพย์", paymentInfoMissing: "ยังไม่ได้ตั้งค่าข้อมูลการชำระเงิน กรุณาติดต่อร้านค้าก่อนโอนเงิน", notConfigured: "ยังไม่ได้ตั้งค่า", paymentSlipRequired: "กรุณาแนบสลิปก่อนยืนยันคำสั่งซื้อ", invalidSlip: "กรุณาเลือกไฟล์รูปภาพขนาดไม่เกิน 5 MB", slipReceived: "แนบสลิปการโอนเงินกับคำสั่งซื้อแล้ว", orderSuccessful: "คำสั่งซื้อเสร็จสมบูรณ์", orderId: "หมายเลขคำสั่งซื้อ",
});

const localeKey = language => String(language || "TH").toUpperCase() === "EN" ? "en" : "th";
export const t = (language, key) => messages[localeKey(language)]?.[key] || messages.en[key] || key;
export const categoryNames = language => ({
  all: t(language, "all"), "new-arrival": t(language, "newArrival"), "t-shirts": t(language, "tees"), hoodies: t(language, "hoodies"), sweatshirts: t(language, "sweatshirts"), "baggy-pants": t(language, "pants"), shorts: t(language, "shorts"), bags: t(language, "bags"), headwear: t(language, "headwear"), underwear: t(language, "underwear"), accessories: t(language, "accessories"), jackets: t(language, "jackets"),
});
